#!/bin/bash

if [ $# -ne 5 ]; then
    echo $0: usage: calipso-start host host_port mongo_port proxy proxy_port
    exit 1
fi

host=$1
host_port=$2
mongo_port=$3
proxy=$4
proxy_port=$5

echo "server $1
user calipso
password calipso_default
auth_db calipso" > /home/calipso/calipso_mongo_access.conf


echo "user admin
password password
url ldap://$host:389
user_id_attribute CN
user_pass_attribute userpassword
user_objectclass inetOrgPerson
user_tree_dn OU=Users,DC=openstack,DC=org
query_scope one
tls_req_cert allow
group_member_attribute member" > /home/calipso/ldap.conf

#unzip /home/calipso/calipso-initial-db.zip

docker run \
-d \
-v /home/calipso/db:/data/db \
-p 27017:27017 \
-p 28017:28017 \
--name calipso-mongo \
korenlev/calipso:mongo

docker run \
-d \
-v /home/calipso:/local_dir \
-p 389:389 \
--name calipso-ldap \
korenlev/calipso:ldap

docker run \
-d \
-e MONGO_CONFIG=/local_dir/calipso_mongo_access.conf \
-e LDAP_CONFIG=/local_dir/ldap.conf \
-e LOG_LEVEL=DEBUG \
-e BIND=0.0.0.0:8000 \
-v /home/calipso:/local_dir \
-p 8000:8000 \
-p 40022:22 \
--name calipso-api \
korenlev/calipso:api

docker run \
-d \
-v /home/calipso:/local_dir \
-e MONGO_CONFIG=/local_dir/calipso_mongo_access.conf \
-e PYTHONPATH=/home/scan/calipso_prod/app \
-p 30022:22 \
--name calipso-scan \
korenlev/calipso:scan

docker run \
-d \
-v /home/calipso:/local_dir \
-e MONGO_CONFIG=/local_dir/calipso_mongo_access.conf \
-e PYTHONPATH=/home/scan/calipso_prod/app \
-p 50022:22 \
--name calipso-listen \
korenlev/calipso:listen

docker run \
-d \
-v /home/calipso:/local_dir \
-e PYTHONPATH=/home/scan/calipso_prod/app \
-p 20022:22 \
-p 3000:3000 \
-p 4567:4567 \
-p 5671:5671 \
-p 15672:15672 \
--name calipso-sensu \
korenlev/calipso:sensu

docker run \
-d \
-e ROOT_URL=http://$host:$host_port \
-e MONGO_URL=mongodb://calipso:calipso_default@$host:$mongo_port/calipso \
-e HTTP_PROXY=http://$proxy:8080 \
-e HTTPS_PROXY=http://$proxy:8080 \
-v /home/calipso/calipso_ui:/bundle \
-p 80:80 \
--name calipso-ui \
korenlev/calipso:ui
