
DEFAULT_OBJECT_TYPE = ""
INSTANCE_OBJECT_TYPE = "instance"
INTERFACE_OBJECT_TYPE = "interface"
NETWORK_OBJECT_TYPE = "network"
PORT_OBJECT_TYPE = "port"
ROUTER_OBJECT_TYPE = "router"
SUBNET_OBJECT_TYPE = "subnet"
